### ISSUE TITLE
Authentication Solution

### ISSUE THREAD

**Issue by EtherTyper** [onyxbits/raccoon4#98]
I was having the same authentication issues as everyone has been reporting recently, but I solved them by enabling 2FA on my Google account and creating an app password for Raccoon. I think they view signing in from a strange application as less suspicious with an app password than with your normal password. You might consider updating the documentation to suggest this process if other people can replicate my results.

**Comment by babyquin** [comment]
oh, thanks so much, you help me alot.

1000 like :)

**Comment by onyxbits** [comment]
Made a note of this in my blogpost: https://raccoon.onyxbits.de/blog/bad-authentication-google-account-blocked/

Though I'm still looking for a better way. My current working theory is that Google partially rolled out an account manager update (A/B testing) that either dropped support for Jelly Bean (Raccoon mimics the JB TLS stack) or factors in something from the environment ("what else came from that IP address?") that results in blocked login attempts.

**Comment by morethanhater** [comment]
this kind of solution seems pretty unstable.
way before, when i openet the first ticket about this problem i did try to auth using app password with no success.
now it works
very unpredicted behaviour...

**Comment by ninhvuhai** [comment]
Looks like google has fixed it. Is there any other way? plz.

**Comment by babyquin** [comment]
> Looks like google has fixed it. Is there any other way? plz.



> Looks like google has fixed it. Is there any other way? plz.

yup, create app password not work anymore.

**Comment by cyberpion-yotam** [comment]
Any news about this? App passwords stopped working for me as well.

**Comment by onyxbits** [comment]
Please try the latest (v4.19.0) version. It might solve the problem.

**Comment by acornsirup** [comment]
v4.19.0 solved the problem for me, thanks.

**Comment by onyxbits** [comment]
@babyquin 
*fixed*

**Comment by babyquin** [comment]
@onyxbits 
thanks, waiting update login method for DummyDroid. :)

**Comment by ninhvuhai** [comment]
> 
> 
> @babyquin
> _fixed_

Thank you so much! you are the best 👍

**Comment by jpstotz** [comment]
Let us see how long the version increase to API level 17 (Android 4.2) will work. 

After disabling Google services for pre 4.x devices Google seems to prepare the next step, now focusing on devices up to Android 4.3: https://www.androidauthority.com/android-jelly-bean-eol-1641403

**Comment by basilgello** [comment]
Do I need to generate new profile to make it work with 4.19.0? I tried logging in with older profile and still get same error:

```java
raccoon -Draccoon.playprofile=d***r --gp-auth
org.apache.http.client.ClientProtocolException: BadAuthentication
	at com.akdeniz.googleplaycrawler.Identity.doPost(Identity.java:192)
	at com.akdeniz.googleplaycrawler.Identity.signIn(Identity.java:153)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.login(GooglePlayAPI.java:319)
	at de.onyxbits.raccoon.cli.Play.auth(Play.java:371)
	at de.onyxbits.raccoon.cli.Router.main(Router.java:137)
	at de.onyxbits.raccoon.Main.main(Main.java:59)
```

**Comment by acornsirup** [comment]
@onyxbits will you post the v4.19 release to Github, too? Thanks!

**Comment by basilgello** [comment]
It is on website & github long ago…  still does not work for me

**Comment by acornsirup** [comment]
v4.19.0 is available on the website as .jar and .exe files (https://raccoon.onyxbits.de/apk-downloader/), but the most current version on Github is still v4.18.0 (https://github.com/onyxbits/raccoon4/releases).

**Comment by onyxbits** [comment]
@acornsirup 

Forgot to push the tags.

*Fixed*

Thanks.
